name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testing on ${{ matrix.os }} and Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node_version }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node_version }}-yarn-
      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{ matrix.node_version }}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node_version}}-jest-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Spelling
        run: yarn lint:spelling
      - name: Types
        run: yarn lint:ts
      - name: Test
        run: yarn test
        env:
          JEST_CI: true
      - name: Build
        run: yarn build
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          verbose: true
